services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  express:
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  caddy:
    profiles:
      - caddy
